rates = read.table('收益率.csv', header=T, sep=',')

library('forecast')
SSEC = auto.arima(rates$SSEC, trace=T)
SCI = auto.arima(rates$SCI, trace=T)
FTSE100 = auto.arima(rates$FTSE100, trace=T)
DAX30 = auto.arima(rates$DAX30, trace=T)
CAC40 = auto.arima(rates$CAC40, trace=T)

SSEC_Res = na.omit(SSEC$residuals)
SCI_Res = na.omit(SCI$residuals)
FTSE100_Res = na.omit(FTSE100$residuals)
DAX30_Res = na.omit(DAX30$residuals)
CAC40_Res = na.omit(CAC40$residuals)

print('残差ADF检验')
print(adf.test(SSEC_Res))
print(adf.test(SCI_Res))
print(adf.test(FTSE100_Res))
print(adf.test(DAX30_Res))
print(adf.test(CAC40_Res))
print('残差BDS检验')
print(bds.test(SSEC_Res))
print(bds.test(SCI_Res))
print(bds.test(FTSE100_Res))
print(bds.test(DAX30_Res))
print(bds.test(CAC40_Res))

# GARCH
print('开始GARCH')
library('fGarch')
library('tseries')
#library('rugarch')
garch = function(seq)
{
  model = garchFit(~garch(1,1), data=seq, trace=F)
  return(model)
}
SSEC_GARCH = garch(SSEC_Res)
SCI_GARCH = garch(SCI_Res)
FTSE100_GARCH = garch(FTSE100_Res)
CAC40_GARCH = garch(CAC40_Res)